name: Deploy Vue to GCP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout code
        uses: actions/checkout@v3

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🧱 Build project
        run: npm run build

      - name: 🔐 Decode SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_KEY_BASE64 }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: 🚀 Deploy to GCP VM
        uses: appleboy/scp-action@master
        with:
          host: 34.60.191.49
          username: s0929834901
          key: ~/.ssh/id_rsa
          source: "dist/*"
          target: "/var/www/marketing_client"
