name: Deploy Vue to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Checkout code
        uses: actions/checkout@v3

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🧱 Build project
        run: npm run build

      - name: ☁️ Setup gcloud with Service Account
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: bold-vent-456911-e4

      - name: 🚀 Upload dist to GCP VM
        run: |
          gcloud compute scp --recurse ./dist/* \
            s0929834901@instance-20250415-114157:/var/www/marketing_client \
            --zone=asia-east1-b
